/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugAboutRouteImport } from './routes/$slug.about'
import { Route as SlugBookRouteImport } from './routes/$slug.book'
import { Route as SlugBookingConfirmedRouteImport } from './routes/$slug.booking-confirmed'
import { Route as SlugCoursesRouteImport } from './routes/$slug.courses'
import { Route as SlugEnquireRouteImport } from './routes/$slug.enquire'
import { Route as SlugReviewsRouteImport } from './routes/$slug.reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAboutRoute = SlugAboutRouteImport.update({
  id: '/$slug/about',
  path: '/$slug/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugBookRoute = SlugBookRouteImport.update({
  id: '/$slug/book',
  path: '/$slug/book',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugBookingConfirmedRoute = SlugBookingConfirmedRouteImport.update({
  id: '/$slug/booking-confirmed',
  path: '/$slug/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCoursesRoute = SlugCoursesRouteImport.update({
  id: '/$slug/courses',
  path: '/$slug/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugEnquireRoute = SlugEnquireRouteImport.update({
  id: '/$slug/enquire',
  path: '/$slug/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugReviewsRoute = SlugReviewsRouteImport.update({
  id: '/$slug/reviews',
  path: '/$slug/reviews',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/book': typeof SlugBookRoute
  '/$slug/booking-confirmed': typeof SlugBookingConfirmedRoute
  '/$slug/courses': typeof SlugCoursesRoute
  '/$slug/enquire': typeof SlugEnquireRoute
  '/$slug/reviews': typeof SlugReviewsRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/book': typeof SlugBookRoute
  '/$slug/booking-confirmed': typeof SlugBookingConfirmedRoute
  '/$slug/courses': typeof SlugCoursesRoute
  '/$slug/enquire': typeof SlugEnquireRoute
  '/$slug/reviews': typeof SlugReviewsRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/book': typeof SlugBookRoute
  '/$slug/booking-confirmed': typeof SlugBookingConfirmedRoute
  '/$slug/courses': typeof SlugCoursesRoute
  '/$slug/enquire': typeof SlugEnquireRoute
  '/$slug/reviews': typeof SlugReviewsRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug/about'
    | '/$slug/book'
    | '/$slug/booking-confirmed'
    | '/$slug/courses'
    | '/$slug/enquire'
    | '/$slug/reviews'
    | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug/about'
    | '/$slug/book'
    | '/$slug/booking-confirmed'
    | '/$slug/courses'
    | '/$slug/enquire'
    | '/$slug/reviews'
    | '/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug/about'
    | '/$slug/book'
    | '/$slug/booking-confirmed'
    | '/$slug/courses'
    | '/$slug/enquire'
    | '/$slug/reviews'
    | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugAboutRoute: typeof SlugAboutRoute
  SlugBookRoute: typeof SlugBookRoute
  SlugBookingConfirmedRoute: typeof SlugBookingConfirmedRoute
  SlugCoursesRoute: typeof SlugCoursesRoute
  SlugEnquireRoute: typeof SlugEnquireRoute
  SlugReviewsRoute: typeof SlugReviewsRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/about': {
      id: '/$slug/about'
      path: '/$slug/about'
      fullPath: '/$slug/about'
      preLoaderRoute: typeof SlugAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/book': {
      id: '/$slug/book'
      path: '/$slug/book'
      fullPath: '/$slug/book'
      preLoaderRoute: typeof SlugBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/booking-confirmed': {
      id: '/$slug/booking-confirmed'
      path: '/$slug/booking-confirmed'
      fullPath: '/$slug/booking-confirmed'
      preLoaderRoute: typeof SlugBookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/courses': {
      id: '/$slug/courses'
      path: '/$slug/courses'
      fullPath: '/$slug/courses'
      preLoaderRoute: typeof SlugCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/enquire': {
      id: '/$slug/enquire'
      path: '/$slug/enquire'
      fullPath: '/$slug/enquire'
      preLoaderRoute: typeof SlugEnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/reviews': {
      id: '/$slug/reviews'
      path: '/$slug/reviews'
      fullPath: '/$slug/reviews'
      preLoaderRoute: typeof SlugReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugAboutRoute: SlugAboutRoute,
  SlugBookRoute: SlugBookRoute,
  SlugBookingConfirmedRoute: SlugBookingConfirmedRoute,
  SlugCoursesRoute: SlugCoursesRoute,
  SlugEnquireRoute: SlugEnquireRoute,
  SlugReviewsRoute: SlugReviewsRoute,
  SlugIndexRoute: SlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
